---
spring:
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
